# name_1 = input("Enter your name")
# name_2 = input("Enter your name ")
# name_3 = input("Enter your name :")
name_4 = input("Enter your name : ")
print(type(name_4))
# print(name_1, name_2, name_3, name_4, sep="\n")